services:
  app:
    build:
      context: .
      dockerfile: Dockerfile  # Указываем путь к Dockerfile в папке calculator
    ports:
      - "4000:8080"  # Проброс порта контейнера на хост
    environment:
      - JAVA_OPTS=-Xmx512m  # Параметры Java (опционально)
